spring:
  application:
    name: termproject

  h2:
    console:
      enabled: true
      path : /h2-console

  datasource:
    # spring.datasource.url= jdbc:postgresql://<<db url>>:<<port>>/<<database>>
    url: jdbc:postgresql://localhost:5432/db2024 #jdbc:h2:mem:test
    driver-class-name: org.postgresql.Driver  #org.h2.Driver
    username: db2024
    password: db2024


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: --
    password: --
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 50000



jwt :
  secret : termprojecttermprojecttermprojecttermproject
  access-token-expiration-time : 8640000



logging:
  level:
    org:
      springframework :
        web: TRACE
        security : TRACE
        hibernate:
          type:
            descriptor:
              sql:
                BasicBinder: TRACE


springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html

  api-docs:
    path: /api-docs

  default-consumes-media-type: application/json

  default-produces-media-type: application/json

  paths-to-match:
    - /api/**

  show-login-endpoint: true